# https://github.com/kmmndr/makefile-collection

COLOR_BLACK=30
COLOR_RED=31
COLOR_GREEN=32
COLOR_YELLOW=33
COLOR_BLUE=34
COLOR_MAGENTA=35
COLOR_CYAN=36
COLOR_WHITE=37

COLOR_FOREGROUND_BLACK := "\\e[${COLOR_BLACK}m"
COLOR_FOREGROUND_RED := "\\e[${COLOR_RED}m"
COLOR_FOREGROUND_GREEN := "\\e[${COLOR_GREEN}m"
COLOR_FOREGROUND_YELLOW := "\\e[${COLOR_YELLOW}m"
COLOR_FOREGROUND_BLUE := "\\e[${COLOR_BLUE}m"
COLOR_FOREGROUND_MAGENTA := "\\e[${COLOR_MAGENTA}m"
COLOR_FOREGROUND_CYAN := "\\e[${COLOR_CYAN}m"
COLOR_FOREGROUND_WHITE := "\\e[${COLOR_WHITE}m"

COLOR_BACKGROUND_BLACK := "\\e[$(shell echo "${COLOR_BLACK}+10"|bc)m"
COLOR_BACKGROUND_RED := "\\e[$(shell echo "${COLOR_RED}+10"|bc)m"
COLOR_BACKGROUND_GREEN := "\\e[$(shell echo "${COLOR_GREEN}+10"|bc)m"
COLOR_BACKGROUND_YELLOW := "\\e[$(shell echo "${COLOR_YELLOW}+10"|bc)m"
COLOR_BACKGROUND_BLUE := "\\e[$(shell echo "${COLOR_BLUE}+10"|bc)m"
COLOR_BACKGROUND_MAGENTA := "\\e[$(shell echo "${COLOR_MAGENTA}+10"|bc)m"
COLOR_BACKGROUND_CYAN := "\\e[$(shell echo "${COLOR_CYAN}+10"|bc)m"
COLOR_BACKGROUND_WHITE := "\\e[$(shell echo "${COLOR_WHITE}+10"|bc)m"

COLOR_RESET := "\\e[0m"

colors:
	@echo -e "- ${COLOR_FOREGROUND_BLACK}COLOR_BLACK${COLOR_RESET}"
	@echo -e "- ${COLOR_FOREGROUND_RED}COLOR_RED${COLOR_RESET}"
	@echo -e "- ${COLOR_FOREGROUND_GREEN}COLOR_GREEN${COLOR_RESET}"
	@echo -e "- ${COLOR_FOREGROUND_YELLOW}COLOR_YELLOW${COLOR_RESET}"
	@echo -e "- ${COLOR_FOREGROUND_BLUE}COLOR_BLUE${COLOR_RESET}"
	@echo -e "- ${COLOR_FOREGROUND_MAGENTA}COLOR_MAGENTA${COLOR_RESET}"
	@echo -e "- ${COLOR_FOREGROUND_CYAN}COLOR_CYAN${COLOR_RESET}"
	@echo -e "- ${COLOR_FOREGROUND_WHITE}COLOR_WHITE${COLOR_RESET}"
	#
	@echo -e "- ${COLOR_BACKGROUND_BLACK}COLOR_BLACK${COLOR_RESET}"
	@echo -e "- ${COLOR_BACKGROUND_RED}COLOR_RED${COLOR_RESET}"
	@echo -e "- ${COLOR_BACKGROUND_GREEN}COLOR_GREEN${COLOR_RESET}"
	@echo -e "- ${COLOR_BACKGROUND_YELLOW}COLOR_YELLOW${COLOR_RESET}"
	@echo -e "- ${COLOR_BACKGROUND_BLUE}COLOR_BLUE${COLOR_RESET}"
	@echo -e "- ${COLOR_BACKGROUND_MAGENTA}COLOR_MAGENTA${COLOR_RESET}"
	@echo -e "- ${COLOR_BACKGROUND_CYAN}COLOR_CYAN${COLOR_RESET}"
	@echo -e "- ${COLOR_BACKGROUND_WHITE}COLOR_WHITE${COLOR_RESET}"
